import type { Metadata } from "next";
import { Outfit, Geist } from "next/font/google";
import Provider from "./provider";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";
import Header from "./_components/Header";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit =Outfit({subsets:['latin']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={outfit.className}
      >
        <ConvexClientProvider>
          <Provider>
            <Header />
          {children}
        </Provider>
        </ConvexClientProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
